export type SupplyRow = {
  requestId: string;
  wagonType: string;
  client: string;
  manager: string;
  shipper: string;
  cargoClass: string;
  weightTons: number;
  wagonsRequested: number;
  mandatory?: number;
  sendStation: string;
  destStation: string;
  returnStation: string;
  turnoverDays: number;
  reposition: number;
  loading: number;
  loadedTransit: number;
  unloading: number;
  returnMovement: number;
  wagonDays: number;
  clientRateKZT: number;
  emptyRateKZT: number;
  loadedRateKZT: number;
  revenueKZT: number;
  dailyRevenueKZT: number;
  totalSumKZT: number;
  sidingDays?: number;
  supplyType: string;
  decade: Array<number | null>;
};
